#pragma once

enum XACT_WAVEBANK_AUDIOPACK : unsigned int
{
    XACT_WAVEBANK_AUDIOPACK_BGM_DEFAULT = 0,
    XACT_WAVEBANK_AUDIOPACK_BGM_CLEAR = 1,
    XACT_WAVEBANK_AUDIOPACK_SE_WAVE = 2,
    XACT_WAVEBANK_AUDIOPACK_SE_WAVE2 = 3,
    XACT_WAVEBANK_AUDIOPACK_SE_CLICK = 4,
    XACT_WAVEBANK_AUDIOPACK_SE_SELECT = 5,
    XACT_WAVEBANK_AUDIOPACK_SE_SLIDE = 6,
};

#define XACT_WAVEBANK_AUDIOPACK_ENTRY_COUNT 7
